// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenusHR.Infrastructure.Presistence;

#nullable disable

namespace VenusHR.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenusHR.Core.Master.AppSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("VenusHR.Core.Master.Hrs_Employees", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ArbName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArbName4S")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("BirthCityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BloodGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("Cost1")
                        .HasColumnType("int");

                    b.Property<int?>("Cost2")
                        .HasColumnType("int");

                    b.Property<int?>("Cost3")
                        .HasColumnType("int");

                    b.Property<int?>("Cost4")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("E_Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExcludeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FamilyArbName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyArbName4S")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyEngName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherArbName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherArbName4S")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherEngName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GosiexcludeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GosijoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gosinumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrandArbName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrandArbName4S")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrandEngName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasTaqat")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsProjectRelated")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSpecialForce")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LaborOfficeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("MachineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<double?>("MaxLoanDedution")
                        .HasColumnType("float");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("OldCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassPortNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegComputerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("int");

                    b.Property<string>("SsnNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Whours")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Hrs_Employees");
                });

            modelBuilder.Entity("VenusHR.Core.Master.SS_RequestActions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.Property<string>("ActionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActionSerial")
                        .HasColumnType("int");

                    b.Property<int>("ConfigID")
                        .HasColumnType("int");

                    b.Property<int>("ConfirmedNoOfdays")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("RequestSerial")
                        .HasColumnType("int");

                    b.Property<int>("SS_EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("SS_RequestActions");
                });

            modelBuilder.Entity("VenusHR.Core.Master.SS_RequestTypes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("RequestArbName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestEngName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("SS_RequestTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
